Repository utooland/utoo, pull requests merged in 2025-06, with the labels that each got.

#1932 fix: is_pkg_lock_outdated not work
  crates/cli/src/helper/lock.rs
Labels: S-Bug-confirmed

#1950 fix: overrides rule parse
  crates/cli/src/helper/package.rs
  crates/cli/src/helper/ruborist.rs
  crates/cli/src/util/node.rs
Labels: S-Bug-confirmed, A-Pkg Manager

#1954 feat: auto set cwd
  crates/cli/src/bin/utoo-deps.rs
  crates/cli/src/bin/utoo-install.rs
  crates/cli/src/cmd/deps.rs
  crates/cli/src/cmd/install.rs
  crates/cli/src/cmd/run.rs
  crates/cli/src/cmd/update.rs
  crates/cli/src/helper/lock.rs
  crates/cli/src/helper/workspace.rs
  crates/cli/src/main.rs
  crates/cli/src/util/json.rs
  crates/cli/src/util/linker.rs
Labels: A-Pkg Manager

#1961 fix: sub package missing check
  crates/cli/src/cmd/deps.rs
  crates/cli/src/helper/lock.rs
Labels: S-Bug-confirmed, A-Pkg Manager

#1963 fix: update createEnv & add externals for library examples
  examples/with-library/project_options.json
  examples/with-library/src/index.ts
  packages/pack/src/index.ts
  packages/pack/src/util.ts
Labels: A-Pack, S-Enhancement

#1960 fix: workspace root path
  crates/cli/src/helper/workspace.rs
Labels: S-Bug-confirmed, A-Pkg Manager

#1968 fix: workspace bin
  crates/cli/src/helper/lock.rs
Labels: S-Bug-confirmed, A-Pkg Manager

#1989 fix(pm): pkg lock outdated check
  crates/cli/src/helper/lock.rs
Labels: A-Pkg Manager

#1995 feat(pm): utx
  crates/cli/src/bin/utoo-rebuild.rs
  crates/cli/src/cmd/deps.rs
  crates/cli/src/cmd/execute.rs
  crates/cli/src/cmd/install.rs
  crates/cli/src/cmd/mod.rs
  crates/cli/src/cmd/rebuild.rs
  crates/cli/src/cmd/run.rs
  crates/cli/src/constants.rs
  crates/cli/src/helper/lock.rs
  crates/cli/src/helper/ruborist.rs
  crates/cli/src/main.rs
  crates/cli/src/service/execute.rs
  crates/cli/src/service/mod.rs
  crates/cli/src/service/package.rs
  crates/cli/src/util/binary_resolver.rs
  crates/cli/src/util/json.rs
  crates/cli/src/util/mod.rs
  crates/cli/src/util/package_installer.rs
  crates/cli/src/util/registry.rs
  vendor/scripts/npm-main.sh
  vendor/templates/utoo.package.json.template
Labels: S-Feature, A-Pkg Manager
