Repository utooland/utoo, pull requests merged in 2025-04, with the labels that each got.

#1794 refact(cli): use utoo-core to load config
  Cargo.lock
  crates/cli/Cargo.toml
  crates/cli/src/main.rs
  crates/cli/src/util/config.rs
  crates/core/src/config.rs
  crates/core/src/lib.rs
  crates/core/src/main.rs
Labels: enhancement

#1799 fix: legacy peer deps
  crates/cli/src/helper/ruborist.rs
Labels: bug

#1798 feat: upgrade deno_ast enable runtime build
  Cargo.lock
  Cargo.toml
  crates/bundler-core/Cargo.toml
  crates/runtime/Cargo.toml
  crates/runtime/src/lib.rs
Labels: enhancement

#1800 chore: ci cache
  .github/workflows/ci.yml
Labels: improvement

#1805 refactor(cli): deno semver match
  Cargo.lock
  crates/cli/Cargo.toml
  crates/cli/src/helper/ruborist.rs
  crates/cli/src/util/node.rs
Labels: bug

#1810 fix: napi prepublish
  .cargo/config.toml
  .github/workflows/bundler-release.yml
  packages/bundler/package.json
Labels: enhancement

#1811 fix: shibang
  packages/bundler/bin/cli.js
Labels: bug

#1821 fix: deps npe
  .github/workflows/release.yml
  Cargo.lock
  crates/cli/Cargo.toml
  crates/cli/src/service/install.rs
  crates/cli/src/util/registry.rs
Labels: bug

#1825 feat: entry filename
  crates/bundler-api/src/library.rs
  crates/bundler-core/src/library/ecmascript/chunk.rs
Labels: enhancement

#1836 fix: linux clonefile exception
  crates/cli/src/util/cloner.rs
Labels: bug

#1838 chore: ubuntu 22.04
  .github/workflows/release.yml
Labels: documentation

#1840 chore: libssl
  .github/workflows/ci.yml
  .github/workflows/release.yml
  crates/cli/Cargo.toml
Labels: documentation

#1842 chore: linux libssl
  Cargo.lock
  crates/cli/Cargo.toml
  crates/cli/src/util/cloner.rs
Labels: documentation

#1844 fix: linux build
  crates/cli/src/util/cloner.rs
Labels: bug

#1845 chore: docker build
  .github/workflows/release.yml
  crates/cli/Cargo.toml
Labels: documentation

#1849 chore: gh
  .github/workflows/release.yml
Labels: documentation

#1850 chore: upload release artifact
  .github/workflows/release.yml
Labels: documentation

#1855 feat: utoo-update
  .github/workflows/release.yml
  Cargo.lock
  crates/cli/Cargo.toml
  crates/cli/src/bin/utoo-update.rs
  crates/cli/src/cmd/mod.rs
  crates/cli/src/cmd/update.rs
  crates/cli/src/constants.rs
  crates/cli/src/helper/mod.rs
  crates/cli/src/helper/ruborist.rs
  crates/cli/src/helper/workspace.rs
  crates/cli/src/main.rs
  crates/cli/src/service/mod.rs
  crates/cli/src/service/update.rs
Labels: enhancement

#1858 feat: enhanced package install with workspace support & dependency controls
  crates/cli/src/bin/utoo-install.rs
  crates/cli/src/cmd/install.rs
  crates/cli/src/cmd/update.rs
  crates/cli/src/constants.rs
  crates/cli/src/helper/lock.rs
  crates/cli/src/main.rs
  crates/cli/src/model/package.rs
  crates/cli/src/service/install.rs
  crates/cli/src/service/script.rs
  crates/cli/src/service/update.rs
  crates/cli/src/util/linker.rs
  crates/cli/src/util/mod.rs
  crates/cli/src/util/save_type.rs
Labels: enhancement

#1860 feat: add utoo run command with full stdio support
  crates/cli/src/cmd/mod.rs
  crates/cli/src/cmd/run.rs
  crates/cli/src/main.rs
  crates/cli/src/service/script.rs
Labels: enhancement

#1864 feat: binary mirror config
  Cargo.lock
  crates/cli/Cargo.toml
  crates/cli/src/constants.rs
  crates/cli/src/main.rs
  crates/cli/src/service/binary.rs
  crates/cli/src/service/install.rs
  crates/cli/src/service/mod.rs
  crates/cli/src/service/script.rs
Labels: enhancement

#1866 feat: global install
  Cargo.lock
  crates/cli/Cargo.toml
  crates/cli/src/cmd/install.rs
  crates/cli/src/helper/auto_update.rs
  crates/cli/src/helper/lock.rs
  crates/cli/src/main.rs
  crates/cli/src/model/package.rs
  crates/cli/src/service/script.rs
Labels: enhancement

#1867 feat: utoo main pkg vendor & release flow
  .github/workflows/release.yml
  Cargo.lock
  crates/core/Cargo.toml
  crates/core/src/config.rs
  crates/core/src/main.rs
  crates/core/src/service/cmd.rs
  crates/core/src/service/mod.rs
  vendor/scripts/npm-utoo.sh
  vendor/templates/postinstall.utoo.sh.template
  vendor/templates/utoo.package.json.template
Labels: enhancement

#1868 chore: vendor scripts mod
  vendor/scripts/npm-utoo.sh
Labels: bug

#1869 fix: utoo vendor
  vendor/templates/utoo.package.json.template
Labels: bug

#1870 fix: binary replace
  vendor/templates/postinstall.sh.template
Labels: bug

#1871 fix: ut link not work
  vendor/scripts/npm-utoo.sh
Labels: bug
